/**
 * Created by Philip on 23.02.2015.
 */

module.exports = {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	INFO_CHANGE: "INFO_CHANGE",
	INFO_SAVE: "INFO_SAVE",
	LISTEN: "LISTEN",
	STOP_LISTEN: "STOP_LISTEN",
	FETCH_LISTENERS: "FETCH_LISTENERS",
	FETCH_LISTENING: "FETCH_LISTENING"
};