---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - app/reducers
    - app/actions
    - app/services
    - stories
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- public/
- "**.test.js"
- "**.spec.js"
