# CircleCI Node.js 8.4 with AWSCLI and CPIO
# shoutit/circleci-node:8.4

FROM circleci/node:8.4

RUN sudo apt-get update && sudo apt-get install -y \
    cpio \
    libpython-dev \
    python-pip

RUN sudo pip install awscli
