FROM node:4

ARG SHOUTIT_API_URL
ARG SHOUTIT_PUBLIC_URL
ARG SHOUTIT_GANALYTICS
ARG NEW_RELIC_LICENSE_KEY
ARG NEW_RELIC_APP_NAME

# Provides cached layer for node_modules
ADD package.json /tmp/package.json
RUN cd /tmp && npm install --production
RUN mkdir -p /src && cp -a /tmp/node_modules /src/

# Define working directory
WORKDIR /src

COPY . /src

EXPOSE 8080

ENV NODE_ENV production
ENV PORT 8080
ENV SHOUTIT_API_URL=$SHOUTIT_API_URL
ENV SHOUTIT_PUBLIC_URL=$SHOUTIT_PUBLIC_URL
ENV SHOUTIT_GANALYTICS=$SHOUTIT_GANALYTICS
ENV NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY
ENV NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME

CMD npm start
