export const LOAD_CONVERSATIONS = "LOAD_CONVERSATIONS";
export const LOAD_CONVERSATIONS_SUCCESS = "LOAD_CONVERSATIONS_SUCCESS";
export const LOAD_CONVERSATIONS_FAILURE = "LOAD_CONVERSATIONS_FAILURE";
