export default {
    // Tag store statuses
    LISTENING_CLICKED: 'LISTENING_CLICKED',
    BUTTON_LISTENED: 'BUTTON_LISTENED',
    BUTTON_UNLISTENED: 'BUTTON_UNLISTENED',
    // User store statuses
    USER_LISTENING_CLICKED: 'USER_LISTENING_CLICKED',
    USER_BUTTON_LISTENED: 'USER_BUTTON_LISTENED',
    USER_BUTTON_UNLISTENED: 'USER_BUTTON_UNLISTENED'
}