export default {
	      SEARCH_ALL: "SEARCH_ALL",
	      SEARCH_ALL_SUCCESS: "SEARCH_ALL_SUCCESS",
	      SEARCH_ALL_CANCEL: "SEARCH_ALL_CANCEL",

	      SEARCH_SHOUTS: "SEARCH_SHOUTS",
	      SEARCH_SHOUTS_SUCCESS: "SEARCH_SHOUTS_SUCCESS",
	      SEARCH_SHOUTS_CANCEL: "SEARCH_SHOUTS_CANCEL",

	      SEARCH_TAGS: "SEARCH_TAGS",
	      SEARCH_TAGS_SUCCESS: "SEARCH_TAGS_SUCCESS",
	      SEARCH_TAGS_CANCEL: "SEARCH_TAGS_CANCEL",

	      SEARCH_USERS: "SEARCH_USERS",
	      SEARCH_USERS_SUCCESS: "SEARCH_USERS_SUCCESS",
	      SEARCH_USERS_CANCEL: "SEARCH_USERS_CANCEL",

	      SEARCH_LOAD_MORE: "SEARCH_LOAD_MORE"
};
