export default {
	SEARCH_TAGS: "SEARCH_TAGS",
	SEARCH_TAGS_SUCCESS: "SEARCH_TAGS_SUCCESS",
	SEARCH_TAGS_CANCEL: "SEARCH_TAGS_CANCEL",

	LOAD_TAG: "LOAD_TAG",
	LOAD_TAG_SUCCESS : "LOAD_TAG_SUCCESS",

	LISTEN_TAG: "LISTEN_TAG",
	LISTEN_TAG_SUCCESS: "LISTEN_TAG_SUCCESS",

	STOP_LISTEN_TAG: "STOP_LISTEN_TAG",
	STOP_LISTEN_TAG_SUCCESS: "STOP_LISTEN_TAG_SUCCESS",

	LOAD_TAG_LISTENERS: "LOAD_TAG_LISTENERS",
	LOAD_TAG_LISTENERS_SUCCESS: "LOAD_TAG_LISTENERS_SUCCESS",

	LOAD_TAG_SHOUTS: "LOAD_TAG_SHOUTS",
	LOAD_TAG_SHOUTS_SUCCESS: "LOAD_TAG_SHOUTS_SUCCESS",

	TAG_REQUEST_FAIL: "TAG_REQUEST_FAIL",

	LOAD_TAGS: "LOAD_TAGS",
	LOAD_TAGS_SUCCESS: "LOAD_TAGS_SUCCESS",
	LOAD_TAGS_FAILED: "LOAD_TAGS_FAILED"
};
