export default {
  SEARCH_TAGS: 'SEARCH_TAGS',
  SEARCH_TAGS_SUCCESS: 'SEARCH_TAGS_SUCCESS',
  SEARCH_TAGS_CANCEL: 'SEARCH_TAGS_CANCEL',

  LOAD_TAG: 'LOAD_TAG',
  LOAD_TAG_SUCCESS: 'LOAD_TAG_SUCCESS',

  LISTEN_TAG: 'LISTEN_TAG',
  LISTEN_TAG_SUCCESS: 'LISTEN_TAG_SUCCESS',
  LISTEN_TAG_FAIL: 'LISTEN_TAG_FAIL',

  STOP_LISTEN_TAG: 'STOP_LISTEN_TAG',
  STOP_LISTEN_TAG_SUCCESS: 'STOP_LISTEN_TAG_SUCCESS',
  STOP_LISTEN_TAG_FAIL: 'STOP_LISTEN_TAG_FAIL',

  LOAD_TAG_LISTENERS: 'LOAD_TAG_LISTENERS',
  LOAD_TAG_LISTENERS_SUCCESS: 'LOAD_TAG_LISTENERS_SUCCESS',

  LOAD_TAG_RELATED: 'LOAD_TAG_RELATED',

  LOAD_TAG_SHOUTS: 'LOAD_TAG_SHOUTS',
  LOAD_TAG_SHOUTS_SUCCESS: 'LOAD_TAG_SHOUTS_SUCCESS',
  LOAD_MORE_TAG_SHOUTS: 'LOAD_MORE_TAG_SHOUTS',

  TAG_REQUEST_FAIL: 'TAG_REQUEST_FAIL',

  LOAD_TAGS: 'LOAD_TAGS',
  LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS',
  LOAD_TAGS_FAILED: 'LOAD_TAGS_FAILED',

  LOAD_TAGS_SPRITE: 'LOAD_TAGS_SPRITE',
  LOAD_TAGS_SPRITE_SUCCESS: 'LOAD_TAGS_SPRITE_SUCCESS',
  LOAD_TAGS_SPRITE_FAILED: 'LOAD_TAGS_SPRITE_FAILED',

  REQUEST_SPRITING: 'REQUEST_SPRITING',
  REQUEST_SPRITING_SUCCESS: 'REQUEST_SPRITING_SUCCESS',
  REQUEST_SPRITING_FAILED: 'REQUEST_SPRITING_FAILED',
};
