export default {
	  UPDATE: "UPDATE",
	  UPDATE_SUCCESS: "UPDATE_SUCCESS",

	  REQUEST_FAILED: "REQUEST_FAILED",

	  LOAD_MORE: "LOAD_MORE",
	  LOAD_MORE_SUCCESS: "LOAD_MORE_SUCCESS",

	  LOAD_RELATED_SHOUTS: "LOAD_RELATED_SHOUTS",
	  LOAD_SHOUT: "LOAD_SHOUT",
	  LOAD_SHOUT_SUCCESS: "LOAD_SHOUT_SUCCESS",
	  LOAD_SHOUT_FAILED: "LOAD_SHOUT_FAILED",

	  CHANGE_SHOUT_DRAFT: "CHANGE_SHOUT_DRAFT",
	  SEND_SHOUT: "SEND_SHOUT",
	  REMOVE_SHOUT_IMAGE: "REMOVE_SHOUT_IMAGE",

	  CHANGE_SHOUT_REPLY_DRAFT: "CHANGE_SHOUT_REPLY_DRAFT",
	  SEND_SHOUT_REPLY: "SEND_SHOUT_REPLY",
	  SEND_SHOUT_REPLY_SUCCESS: "SEND_SHOUT_REPLY_SUCCESS",
	  CONVERSATION_CREATED: "CONVERSATION_CREATED",
	  SEND_SHOUT_REPLY_FAILED: "SEND_SHOUT_REPLY_FAILED"
};
