export default {
	UPDATE: "UPDATE",
	UPDATE_SUCCESS: "UPDATE_SUCCESS",

	REQUEST_FAILED: "REQUEST_FAILED",

	LOAD_MORE: "LOAD_MORE",
	LOAD_MORE_SUCCESS: "LOAD_MORE_SUCCESS",

	LOAD_SHOUT: "LOAD_SHOUT",
	LOAD_SHOUT_SUCCESS: "LOAD_SHOUT_SUCCESS",
	LOAD_SHOUT_FAILED: "LOAD_SHOUT_FAILED",

	CHANGE_SHOUT_DRAFT: "CHANGE_SHOUT_DRAFT",
	SEND_SHOUT: "SEND_SHOUT"
};
