/**
 * Created by Philip on 26.02.2015.
 */

module.exports = {
	UPDATE: "UPDATE",
	UPDATE_SUCCESS: "UPDATE_SUCCESS",
	REQUEST_FAILED: "REQUEST_FAILED",
	LOAD_MORE: "LOAD_MORE",
	LOAD_MORE_SUCCESS: "LOAD_MORE_SUCCESS"
};
