export const VIDEOCALL_INIT = "VIDEOCALL_INIT";
export const VIDEOCALL_INIT_SUCCESS = "VIDEOCALL_INIT_SUCCESS";
export const VIDEOCALL_INIT_FAILURE = "VIDEOCALL_INIT_FAILURE";
export const VIDEOCALL_INVITE = "VIDEOCALL_INVITE";
export const VIDEOCALL_INVITE_SUCCESS = "VIDEOCALL_INVITE_SUCCESS";
export const VIDEOCALL_INVITE_FAILURE = "VIDEOCALL_INVITE_FAILURE";
