export default {
    LOAD_DISCOVER_WITH_CODE: "LOAD_DISCOVER_WITH_CODE",
    LOAD_DISCOVER_WITH_CODE_SUCCESS: "LOAD_DISCOVER_WITH_CODE_SUCCESS",
    LOAD_DISCOVER_WITH_ID: "LOAD_DISCOVER_WITH_ID",
    LOAD_DISCOVER_WITH_ID_SUCCESS: "LOAD_DISCOVER_WITH_ID_SUCCESS",
    LOAD_DISCOVER_WITH_ID_FAIL: "LOAD_DISCOVER_WITH_ID_FAIL",
    LOAD_DISCOVER_SHOUTS: "LOAD_DISCOVER_SHOUTS",
    LOAD_DISCOVER_SHOUTS_SUCCESS: "LOAD_DISCOVER_SHOUTS_SUCCESS",
    LOAD_DISCOVER_SHOUTS_FAIL: "LOAD_DISCOVER_SHOUTS_FAIL",
    LOAD_DISCOVER_FAIL: "LOAD_DISCOVER_FAIL",
};