/**
 * Created by Philip on 23.02.2015.
 */

export default {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",

    INFO_CHANGE: "INFO_CHANGE",
    INFO_SAVE: "INFO_SAVE",

    LISTEN: "LISTEN",
    STOP_LISTEN: "STOP_LISTEN",

    LOAD_USER_LISTENERS: "LOAD_USER_LISTENERS",
    LOAD_USER_LISTENING: "LOAD_USER_LISTENING",

    LOAD_USER: "LOAD_USER",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",

    LOAD_USER_SHOUTS: "LOAD_USER_SHOUTS",
    LOAD_USER_SHOUTS_SUCCESS: "LOAD_USER_SHOUTS_SUCCESS",

    LOAD_MORE_USER_SHOUTS: "LOAD_MORE_USER_SHOUTS",
    LOAD_MORE_USER_SHOUTS_SUCCESS: "LOAD_MORE_USER_SHOUTS_SUCCESS"
};
