/**
 * Created by Philip on 23.02.2015.
 */

export default {
    FORGET_RESULT: "FORGET_RESULT",
    RESEDND_EMAIL_VERIF: "RESEDND_EMAIL_VERIF",

    SIGNUP: "SIGNUP",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    LOGIN: "LOGIN",
    LOGIN_FB_ERROR: "LOGIN_FB_ERROR",
    
    LOGOUT: "LOGOUT",

    INFO_CHANGE: "INFO_CHANGE",
    INFO_SAVE: "INFO_SAVE",
    PASS_CHANGE: "PASS_CHANGE",

    LISTEN: "LISTEN",
    STOP_LISTEN: "STOP_LISTEN",

    LOAD_USER_LISTENERS: "LOAD_USER_LISTENERS",
    LOAD_USER_LISTENING: "LOAD_USER_LISTENING",

    LOAD_USER: "LOAD_USER",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",

    LOAD_USER_SHOUTS: "LOAD_USER_SHOUTS",
    LOAD_USER_SHOUTS_SUCCESS: "LOAD_USER_SHOUTS_SUCCESS",

    LOAD_MORE_USER_SHOUTS: "LOAD_MORE_USER_SHOUTS",
    LOAD_MORE_USER_SHOUTS_SUCCESS: "LOAD_MORE_USER_SHOUTS_SUCCESS",

    SHOW_DOWNLOAD_POPUP: "SHOW_DOWNLOAD_POPUP",
    HIDE_DOWNLOAD_POPUP: "HIDE_DOWNLOAD_POPUP"
};
