/**
 * Created by Philip on 23.02.2015.
 */

export default {
  PROFILE_CHANGE: 'PROFILE_CHANGE',
  PROFILE_CHANGES_SAVE: 'PROFILE_CHANGES_SAVE',
  PROFILE_PICTURE_UPLOAD: 'PROFILE_PICTURE_UPLOAD',
  COVER_IMAGE_UPLOAD: 'COVER_IMAGE_UPLOAD',

  INFO_CHANGE: 'INFO_CHANGE',
  INFO_SAVE: 'INFO_SAVE',
  PASS_CHANGE: 'PASS_CHANGE',

  LISTEN: 'LISTEN',
  STOP_LISTEN: 'STOP_LISTEN',
  LISTEN_SUCCESS: 'LISTEN_SUCCESS',
  STOP_LISTEN_SUCCESS: 'STOP_LISTEN_SUCCESS',
  LISTEN_FAIL: 'LISTEN_FAIL',
  STOP_LISTEN_FAIL: 'STOP_LISTEN_FAIL',

  LOAD_USER_LISTENERS: 'LOAD_USER_LISTENERS',
  LOAD_MORE_USER_LISTENERS: 'LOAD_MORE_USER_LISTENERS',

  LOAD_LISTENING: 'LOAD_LISTENING',
  LOAD_MORE_USER_LISTENING: 'LOAD_MORE_USER_LISTENING',

  LOAD_USER_TAGS: 'LOAD_USER_TAGS',
  LOAD_USER_TAGS_SUCCESS: 'LOAD_USER_TAGS_SUCCESS',
  LOAD_USER_TAGS_FAIL: 'LOAD_USER_TAGS_FAIL',
  LOAD_MORE_USER_TAGS: 'LOAD_MORE_USER_TAGS',

  LOAD_USER: 'LOAD_USER',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',

  LOAD_USER_SHOUTS: 'LOAD_USER_SHOUTS',
  LOAD_USER_SHOUTS_SUCCESS: 'LOAD_USER_SHOUTS_SUCCESS',

  LOAD_MORE_USER_SHOUTS: 'LOAD_MORE_USER_SHOUTS',
  LOAD_MORE_USER_SHOUTS_SUCCESS: 'LOAD_MORE_USER_SHOUTS_SUCCESS',

  SHOW_DOWNLOAD_POPUP: 'SHOW_DOWNLOAD_POPUP',
  HIDE_DOWNLOAD_POPUP: 'HIDE_DOWNLOAD_POPUP',
};
