/**
 * Created by Philip on 22.06.2015.
 */

export default {
  LOAD_NOTIFICATIONS: 'LOAD_NOTIFICATIONS',
  LOAD_NOTIFICATIONS_SUCCESS: 'LOAD_NOTIFICATIONS_SUCCESS',
  LOAD_NOTIFICATIONS_FAILED: 'LOAD_NOTIFICATIONS_FAILED',

  LOAD_MORE_NOTIFICATIONS: 'LOAD_MORE_NOTIFICATIONS',
  LOAD_MORE_NOTIFICATIONS_SUCCESS: 'LOAD_MORE_NOTIFICATIONS_SUCCESS',
  LOAD_MORE_NOTIFICATIONS_FAILED: 'LOAD_MORE_NOTIFICATIONS_FAILED',

  RESET_NOTIFICATIONS: 'RESET_NOTIFICATIONS',
  RESET_NOTIFICATIONS_SUCCESS: 'RESET_NOTIFICATIONS_SUCCESS',
  RESET_NOTIFICATIONS_FAILED: 'RESET_NOTIFICATIONS_FAILED',

  READ_NOTIFICATION: 'READ_NOTIFICATION',
  READ_NOTIFICATION_SUCCESS: 'READ_NOTIFICATION_SUCCESS',
  READ_NOTIFICATION_FAILED: 'READ_NOTIFICATION_FAILED',

  UNREAD_NOTIFICATION: 'UNREAD_NOTIFICATION',
  UNREAD_NOTIFICATION_SUCCESS: 'UNREAD_NOTIFICATION_SUCCESS',
  UNREAD_NOTIFICATION_FAILED: 'UNREAD_NOTIFICATION_FAILED'
};
