export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const LOAD_NEXT_MESSAGES = "LOAD_NEXT_MESSAGES";
export const LOAD_PREVIOUS_MESSAGES = "LOAD_PREVIOUS_MESSAGES";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_FAILURE = "LOAD_MESSAGES_FAILURE";
export const CONVERSATION_DRAFT_CHANGE = "CONVERSATION_DRAFT_CHANGE";
